name: Hourly Notice Checker

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘণ্টা পর পর ক্লাউডে স্বয়ংক্রিয়ভাবে চলবে
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests bs4 aiohttp

      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python telegram_bot.py

      - name: Save History
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add downloaded_history.txt
          git commit -m "Update download history" || exit 0
          git push
